config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :nodes, path: 'files', only: [:show, :index, :create, :new] do
    collection do
      post :upload
    end
    member do
      get :sharing
      post :share
      post :tagging
    end
  end

  resources :sharings, only: [:show, :index]

  resources :questionnaires do
    get :sharing, :alert_answered, on: :member
    post :share, on: :member
    resources :questions
  end

  get '/labels', to: 'home#labels'
  get 'quizzes', to: 'quizzes#index'
  get 'quizzes/take/:questionnaire_id', to: 'quizzes#take', as: :take_quizzes
  get 'quizzes/result/:questionnaire_id', to: 'quizzes#result', as: :result_quizzes
  post 'quizzes/answer/:questionnaire_id', to: 'quizzes#answer', as: :answer_quizzes

  root to: 'nodes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/file_node.rb
class FileNode < ApplicationRecord
  NODE_TYPES = {
    folder: "folder",
    file: "file"
  }

  belongs_to :parent, class_name: 'FileNode', optional: true
  has_many :children, class_name: 'FileNode', foreign_key: :parent_id
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id, optional: true

  has_and_belongs_to_many :users

  mount_uploader :file, FileUploader

  acts_as_list scope: :parent_id
  acts_as_taggable_on :labels

  scope :roots, -> { where(parent_id: nil) }
  scope :folders, -> { where(node_type: NODE_TYPES[:folder])}
  scope :files, -> { where(node_type: NODE_TYPES[:file]) }

  scope :by_name, -> { order('name asc') }

  before_save :caching_ancestry_values


  validates :node_type, presence: true
  validate :maximum_file_size

  def is_folder?
    self.node_type == NODE_TYPES[:folder]
  end

  def is_file?
    self.node_type == NODE_TYPES[:file]
  end

  # from parent, grandparent, great grandparent...
  def ancestor_ids
    self.ancestry.split('/').select{|s| !s.blank?}.map{|a| a.to_i}.reverse
  end

  # get parent, grandparent, and great grandparent
  def ancestors
    FileNode.where(id: ancestor_ids).order("LENGTH(ancestry) DESC")
  end

  def descendants
    where("LOWER(ancestry) LIKE ?", "#{self.ancestry}#{self.id}/%")
  end

  def add_child(node)
    node.parent_id = self.id
    node.save
  end

  def can_view_by_user?(user)
    owner_id == user.id ||
    user.accessible_file_nodes.pluck(:id).include?(self.id) ||
    (user.accessible_file_nodes.pluck(:id) & ancestor_ids).any?
  end

  def can_access_by_user?(user)
    self.owner_id == user.id || user.accessible_file_node_ids.include?(self.id) || self.ancestor_ids.select{|nid| user.accessible_file_node_ids.include?(nid)}.count > 0
  end

  private
  def caching_ancestry_values
    if self.parent
      self.ancestry = "#{parent.ancestry}#{self.parent_id}/"
    else
      self.ancestry = '/'
    end
  end


  def maximum_file_size
    if file && file.size > 50.megabytes
      errors.add(:file, "can not be greater than 50MB")
    end
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController

  def index
    @nodes = my_nodes.roots.by_name.page(params[:page])
  end

  def show
    @file_node = my_nodes.find(params[:id])
    @nodes = @file_node.children.by_name.page(params[:page])
  end

  def new
    @parent_node = my_nodes.folders.find_by_id(params[:parent_id])
    @file_node = my_nodes.folders.new(owner_id: current_user.id, parent_id: @parent_node.try(:id))
  end

  def create
    @parent_node = my_nodes.folders.find_by(id: node_param[:parent_id])
    @file_node = my_nodes.folders.new(node_param)
    @file_node.parent_id = @parent_node.try(:id)
    @file_node.owner_id = current_user.id
    if @file_node.save
      redirect_to nodes_path
    else
      render :new
    end
  end

  def upload
    @parent_node = my_nodes.folders.find_by(id: params[:parent_id])
    @file_node = my_nodes.files.new(owner_id: current_user.id)
    if params[:files] && file = params[:files].first
      @file_node.file = file
      @file_node.parent_id = @parent_node.try(:id)
      @file_node.name = file.original_filename
      @file_node.file_size = file.size
    end
    if @file_node.save
      render json: {status: 'OK'}
    else
      render json: {status: 'ERROR', message: @file_node.errors.full_messages.join(', ')}
    end
  end


  def sharing
    @file_node = my_nodes.find(params[:id])
  end

  def share
    @file_node = my_nodes.find(params[:id])
    @file_node.user_ids = share_param[:user_ids]
    redirect_to node_path(@file_node.parent || @file_node)
  end


  def tagging
    @file_node = current_user.my_files.find(params[:id])
    @file_node.label_list = params[:tags]
    if @file_node.save
      render body: nil, status: 200
    else
      render body: nil, status: 400
    end
  end

  private

  def node_param
    params.require(:file_node).permit(:name, :file, :parent_id)
  end

  def share_param
    params.require(:file_node).permit(:user_ids => [])
  end

  def my_nodes
    current_user.file_nodes
  end

  # prevent nesting file node
  def ensure_nesting_folder
    if @file_node.is_file?
      redirect_to nodes_path
    end
  end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_fileupload.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="modal-uploader">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Upload to Evaluation</h4>
      </div>
      <div class="modal-body">
        <div class="modal-data">
          <p class='text-info'>
            Choose file to upload to your Evaluation
          </p>
        </div>
        <div class="text-right modal-actions">
          <label class="btn btn-primary">
            <!-- <input id="fileupload" type="file" data-parent-id="<%= @file_node.try(:id) %>" multiple="false" style="display: none;" accept='image/jpg,image/jpeg,image/png'> -->
            <input id="fileupload" type="file" data-parent-id="<%= @file_node.try(:id) %>" multiple="false" style="display: none;">
            <span>
              Choose file
            </span>
            </label>
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </div>

      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<script>
  $(document).ready(function () {
      jsUploader('#fileupload', '#modal-uploader', "<%= upload_nodes_path %>");
  });
</script>

app/views/nodes/_form.html.haml
= simple_form_for @file_node, url: nodes_path, method: :post do |f|
  = f.input :name
  = f.hidden_field :parent_id, value: params[:parent_id]
  = f.submit 'Save', class: 'btn btn-primary'

app/views/nodes/_list.html.haml
%table.table.table-striped
  %thead
    %tr
      %th
        Name
      %th
        Modified
      %th
        Labels
      %th
        Additional sharing
  %tbody
    - if @file_node
      %tr
        - if @file_node.parent
          %th= link_to "...", node_path(@file_node.parent)
        - else
          %th= link_to "Home", nodes_path
        %th
        %th
        %th
    - nodes.each do |node|
      = render partial: 'nodes/list_row', locals: {node: node}
.text-center
  = paginate nodes

app/views/nodes/_list_row.html.haml
%tr
  %th
    - if node.is_file?
      %i.fa.fa-file-o
      = node.name
    - else
      %i.fa.fa-folder-o
      = link_to node.name, node_path(node)
  %th
    - if node.is_file?
      = node.updated_at.strftime('%m/%d/%Y %H:%M')
    - else
      \-.-
  %th
    - if node.is_file?
      %input.form-control.taggable-tagsinput(type="text" value="#{node.label_list.join(',')}" placeholder="file label..." data-id="#{node.id}" data-tag-url="#{tagging_node_path(node)}")
  %th
    - node.users.each do |user|
      %span.label.label-success= user.name

    = link_to sharing_node_path(node), remote: true, title: "Share #{node.name}", class: 'pull-right' do
      %i.fa.fa-share(aria-hidden="true")
    - if node.is_file?
      = link_to node.file.url, title: "Download file #{node.name}", class: 'pull-right', target: '_blank' do
        &nbsp;
        %i.fa.fa-download(aria-hidden="true")
        &nbsp;

app/views/nodes/_sharing_modal.html.haml
= form_for file_node, url: share_node_path(file_node), method: :post do |f|
  .modal-header
    %button(type="button" class="close" data-dismiss="modal" aria-label="Close")
      %span(aria-hidden="true")
        &times;
    %h4.modal-title
      %i.fa.fa-share-alt
      Share
      %strong.color-blue= file_node.name
      with
  .modal-body
    %p
      .form-group
        = text_field_tag "file_node[user_ids][]", nil, class: 'form-control', id: 'tokenfield', placeholder: 'Enter name...'
    %div

  .modal-footer
    %button(type="button" class="btn btn-default" data-dismiss="modal")
      Close
    %button(type="button" class="btn btn-primary" type="submit")
      Share

app/views/nodes/index.html.haml
%h1
  Files
  %span.pull-right
    = link_to new_node_path(parent_id: @parent.try(:id)), class: 'btn btn-primary', title: 'New Folder' do
      %i.fa.fa-folder-o
      New Folder
    = link_to '#', class: 'btn btn-success', title: 'Add File', 'data-toggle' => "modal", 'data-target' => "#modal-uploader" do
      %i.fa.fa-file-o
      Add File
.progress-bar
= render partial: 'nodes/list', locals: {nodes: @nodes}

= render partial: 'nodes/fileupload'

#sharingModal.modal.fade(tabindex="-1" role="dialog")
  .modal-dialog(role="document")
    .modal-content

app/views/nodes/new.html.haml
%h1
  New Folder
  %span.pull-right
    -# %input#fileupload(title="Upload file" type="file")
    -#   %i.fa.fa-file-o

= render partial: 'form'

app/views/nodes/sharing.js.haml
$('#sharingModal .modal-content').html("#{escape_javascript(render partial: 'sharing_modal', locals: {file_node: @file_node}) }");
$('#sharingModal').modal('show');

bindTokenInput('#tokenfield', #{raw User.where.not(id: current_user.id).map{|u| {id: u.id, name: u.name}}.to_json}, #{raw @file_node.users.map{|u| {id: u.id, name: u.name}}.to_json})

app/views/nodes/show.html.haml
%h1
  = @file_node.name
  %span.pull-right
    -# %input#fileupload(title="Upload file" type="file")
    -#   %i.fa.fa-file-o
    = link_to new_node_path(parent_id: @file_node.try(:id)), class: 'btn btn-primary', title: 'New Folder' do
      %i.fa.fa-folder-o
      New Folder

    = link_to '#', class: 'btn btn-success', title: 'Add File', 'data-toggle' => "modal", 'data-target' => "#modal-uploader" do
      %i.fa.fa-file-o
      Add File      
.progress-bar
= render partial: 'nodes/list', locals: {nodes: @nodes}

= render partial: 'nodes/fileupload'


#sharingModal.modal.fade(tabindex="-1" role="dialog")
  .modal-dialog(role="document")
    .modal-content