config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :nodes, path: 'files', only: [:show, :index, :create, :new] do
    collection do
      post :upload
    end
    member do
      get :sharing
      post :share
      post :tagging
    end
  end

  resources :sharings, only: [:show, :index]

  resources :questionnaires do
    get :sharing, :alert_answered, on: :member
    post :share, on: :member
    resources :questions
  end

  get '/labels', to: 'home#labels'
  get 'quizzes', to: 'quizzes#index'
  get 'quizzes/take/:questionnaire_id', to: 'quizzes#take', as: :take_quizzes
  get 'quizzes/result/:questionnaire_id', to: 'quizzes#result', as: :result_quizzes
  post 'quizzes/answer/:questionnaire_id', to: 'quizzes#answer', as: :answer_quizzes

  root to: 'nodes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord

  belongs_to :owner, class_name: 'User', foreign_key: :owner_id
  has_many :questions, dependent: :destroy

  has_and_belongs_to_many :users

  validates :name, presence: true
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_questionnaire, only: [:show, :edit, :update, :destroy, :alert_answered]

  def index
    @questionnaires = current_user.questionnaires.page(params[:page])
  end

  def show
  end

  def new
    @questionnaire = Questionnaire.new
  end

  def edit
  end

  def create
    @questionnaire = Questionnaire.new(questionnaire_params)
    @questionnaire.owner = current_user
    if @questionnaire.save
      redirect_to @questionnaire, notice: 'Questionnaire was successfully created.'
    else
      render :new
    end
  end

  def update
    if @questionnaire.update(questionnaire_params)
      redirect_to @questionnaire, notice: 'Questionnaire was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @questionnaire.destroy
    redirect_to questionnaires_url, notice: 'Questionnaire was successfully destroyed.'
  end

  def sharing
    @questionnaire = current_user.questionnaires.find(params[:id])
  end

  def share
    @questionnaire = current_user.questionnaires.find(params[:id])
    @questionnaire.user_ids = share_param[:user_ids]
    redirect_to questionnaires_path
  end

  def alert_answered
    @user = User.find params[:user_id]
    if @user.user_quizzes.where(questionnaire: @questionnaire).count == 0
      @message = "#{@user.name} has not taken the quiz yet"
    end
  end

  private

    def set_questionnaire
      @questionnaire = current_user.questionnaires.find(params[:id])
    end

    def questionnaire_params
      params.require(:questionnaire).permit(:name)
    end

    def share_param
      params.require(:questionnaire).permit(:user_ids => [])
    end
end

app/views/questionnaires/_alert_answered_modal.html.haml
.modal-header
  %button(type="button" class="close" data-dismiss="modal" aria-label="Close")
    %span(aria-hidden="true")
      &times;
  %h4.modal-title
    Alert
.modal-body
  %p= message

.modal-footer
  %button(type="button" class="btn btn-default" data-dismiss="modal")
    Close

app/views/questionnaires/_form.html.haml
= simple_form_for(@questionnaire) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/questionnaires/_sharing_modal.html.haml
= form_for questionnaire, url: share_questionnaire_path(questionnaire), method: :post do |f|
  .modal-header
    %button(type="button" class="close" data-dismiss="modal" aria-label="Close")
      %span(aria-hidden="true")
        &times;
    %h4.modal-title
      %i.fa.fa-share-alt
      Share
      %strong.color-blue= questionnaire.name
      with
  .modal-body
    %p
      .form-group
        = text_field_tag "questionnaire[user_ids][]", nil, class: 'form-control', id: 'tokenfield', placeholder: 'Enter name...'
    %div

  .modal-footer
    %button(type="button" class="btn btn-default" data-dismiss="modal")
      Close
    %button(type="button" class="btn btn-primary" type="submit")
      Save changes

app/views/questionnaires/alert_answered.js.haml
- if @message
  $('#alertModal .modal-content').html("#{escape_javascript(render partial: 'alert_answered_modal', locals: {message: @message}) }");
  $('#alertModal').modal('show');
- else
  location.href = "#{result_quizzes_url(questionnaire_id: @questionnaire, user_id: @user.id)}"

app/views/questionnaires/edit.html.haml
%h1 Editing questionnaire

= link_to 'Show', @questionnaire
\|
= link_to 'Back', questionnaires_path

= render 'form'

app/views/questionnaires/index.html.haml
%h1 Listing questionnaires

= link_to 'New Questionnaire', new_questionnaire_path

%table.table.table-hover
  %thead
    %tr
      %th Name
      %th Shared users
      %th Questions count
      %th
      %th
      %th
      %th
  %tbody
    - @questionnaires.each do |questionnaire|
      %tr
        %td= questionnaire.name
        %td
          - questionnaire.users.each_with_index do |u, index|
            - if index > 0
              \|
            = link_to u.name, alert_answered_questionnaire_path(questionnaire, user_id: u.id), remote: true
        %td.w200= questionnaire.questions.count
        %td.wbtn= link_to 'Show', questionnaire
        %td.wbtn= link_to 'Edit', edit_questionnaire_path(questionnaire)
        %td.wbtn= link_to 'Destroy', questionnaire, :method => :delete, :data => { :confirm => 'Are you sure?' } if questionnaire.owner == current_user
        %td.wbtn
          - if questionnaire.owner == current_user
            = link_to sharing_questionnaire_path(questionnaire), remote: true, class: 'pull-right' do
              %i.fa.fa-share(aria-hidden="true")

#sharingModal.modal.fade(tabindex="-1" role="dialog")
  .modal-dialog
    .modal-content

#alertModal.modal.fade(tabindex="-1" role="dialog")
  .modal-dialog
    .modal-content

app/views/questionnaires/new.html.haml
%h1 New questionnaire

= link_to 'Back', questionnaires_path
= render 'form'

app/views/questionnaires/sharing.js.haml
$('#sharingModal .modal-content').html("#{escape_javascript(render partial: 'sharing_modal', locals: {questionnaire: @questionnaire}) }");
$('#sharingModal').modal('show');

bindTokenInput('#tokenfield', #{raw User.where.not(id: current_user.id).map{|u| {id: u.id, name: u.name}}.to_json}, #{raw @questionnaire.users.map{|u| {id: u.id, name: u.name}}.to_json})

app/views/questionnaires/show.html.haml
%p#notice= notice

= link_to 'Edit', edit_questionnaire_path(@questionnaire)
\|
= link_to 'Back', questionnaires_path
\|
= link_to 'Add question', new_questionnaire_question_path(questionnaire_id: @questionnaire)

%h1= @questionnaire.name


- if @questionnaire.questions.count > 0
  = render 'questions/list', questions: @questionnaire.questions