config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :nodes, path: 'files', only: [:show, :index, :create, :new] do
    collection do
      post :upload
    end
    member do
      get :sharing
      post :share
      post :tagging
    end
  end

  resources :sharings, only: [:show, :index]

  resources :questionnaires do
    get :sharing, :alert_answered, on: :member
    post :share, on: :member
    resources :questions
  end

  get '/labels', to: 'home#labels'
  get 'quizzes', to: 'quizzes#index'
  get 'quizzes/take/:questionnaire_id', to: 'quizzes#take', as: :take_quizzes
  get 'quizzes/result/:questionnaire_id', to: 'quizzes#result', as: :result_quizzes
  post 'quizzes/answer/:questionnaire_id', to: 'quizzes#answer', as: :answer_quizzes

  root to: 'nodes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Evaluation', root_url, class: "navbar-brand large-brand"
    .collapse.navbar-collapse
      - if current_user
        %ul.nav.navbar-nav
          %li{class: current_path?(/questionnaire/)}= link_to "Questionnaires", questionnaires_path
          %li{class: current_path?(/quizzes/)}= link_to "Quizzes", quizzes_path
          %li{class: current_path?(/files/)}= link_to "Files", nodes_path
          %li{class: current_path?(/sharings/)}= link_to "Shared", sharings_path
          %li{class: current_path?(/labels/)}= link_to "Labels", labels_path
        %ul.nav.navbar-nav.navbar-right.pull-right
          %li
            %a(type="button" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false")
              %i.fa.fa-user
              = current_user.name
              %span.caret
            %ul.dropdown-menu
              %li
                %a Setting
                %a{href: destroy_user_session_path, title: 'Sign out'}
                  Sign out

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Evaluation"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all", 'data-turbolinks-track': 'reload'
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application", 'data-turbolinks-track': 'reload'


  %body
    %header
      = render 'layouts/navigation'

    %main.container
      .row#flash-messages
      = yield

      %footer
        //%p &copy; Company 2016